services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${HTTPS_PORT}:443"
    volumes:
      - ./frontend/certs:/certs:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SSL_CERT_PATH=${CONTAINER_SSL_CERT_PATH}
      - SSL_CERT_KEY_PATH=${CONTAINER_SSL_CERT_KEY_PATH}
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}
      - DJANGO_SECRET_KEY=${PROD_DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${PROD_DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${PROD_DJANGO_ALLOWED_HOSTS}
      - DJANGO_CORS_ALLOWED_ORIGINS=${DJANGO_CORS_ALLOWED_ORIGINS}
      - JWT_ACCESS_TOKEN_LIFETIME=${JWT_ACCESS_TOKEN_LIFETIME}
      - JWT_REFRESH_TOKEN_LIFETIME=${JWT_REFRESH_TOKEN_LIFETIME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - OAUTH_42_CLIENT_ID=${OAUTH_42_CLIENT_ID}
      - OAUTH_42_CLIENT_SECRET=${OAUTH_42_CLIENT_SECRET}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -h postgres"]
      interval: 1s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGUSER=${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
